variables:  # global variables section
  PIPELINE_VERSION: &pipeline-tag v2

include:
  - project: 'mambucom/product/sre/release-engineering/templates/gitlab-ci-pipeline'
    ref: *pipeline-tag
    file: '/gitlab/code-quality.yml'

image: registry.gitlab.com/mambucom/product/sre/release-engineering/selfmanagedservices/tools/docker/python:3.9-bullseye

stages:
  - test

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' || $CI_PIPELINE_SOURCE == 'web'
    - if: $CI_COMMIT_BRANCH =~ /^release\/[0-9]+/

unit-test-job:
  stage: test
  before_script:
    - python3 -m pip install --upgrade -r requirements.txt
    - python3 -m pip install --upgrade -r requirements_ci.txt
  script:
    - echo "Running unit tests..."
    - coverage run --source=tap_mambu/tap_mambu_refactor -m pytest refactor_tests
    - coverage json
    - python3 -c "import json; coverage_json = json.loads(open('coverage.json', 'r').read()); print('Coverage is', round(coverage_json['totals']['percent_covered'], 2))"

lint-test-job:
  stage: test
  before_script:
    - python3 -m pip install --upgrade -r requirements.txt
    - python3 -m pip install --upgrade -r requirements_ci.txt
  script:
    - echo "Linting code..."
    - pylint tap_mambu/tap_mambu_refactor --exit-zero
    - pylint tap_mambu/tap_mambu_refactor -d C -d R -d W || true
