include:
  - template: Code-Quality.gitlab-ci.yml

image:
  python:3.10-bullseye

stages:
  - test

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' || $CI_PIPELINE_SOURCE == 'web'
    - if: $CI_COMMIT_BRANCH =~ /^release\/[0-9]+/
unit-test-job:
  stage: test
  before_script:
    - python3 -m pip install --upgrade -r requirements.txt
    - python3 -m pip install --upgrade -r requirements_ci.txt
  script:
    - echo "Running unit tests..."
    - coverage run --source=tap_mambu/tap_mambu_refactor -m pytest tests/refactor_tests
    - coverage json
    - python3 -c "import json; coverage_json = json.loads(open('coverage.json', 'r').read()); print('Coverage is', round(coverage_json['totals']['percent_covered'], 2))"

lint-test-job:
  stage: test
  before_script:
    - python3 -m pip install --upgrade -r requirements.txt
    - python3 -m pip install --upgrade -r requirements_ci.txt
  script:
    - echo "Linting code..."
    - pylint tap_mambu/tap_mambu_refactor --exit-zero
    - pylint tap_mambu/tap_mambu_refactor -d C -d R -d W || true

snyk-dependency-test-job:
  image:
    snyk/snyk-cli:python-3.9
    # registry.gitlab.com/mambucom/product/sre/release-engineering/selfmanagedservices/tools/docker/snyk/snyk-cli:python-3.9
  stage: test
  before_script:
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install --upgrade "setuptools<58"
    - pip install wheel
    - pip install -e .[dev]
    - pip freeze > requirements.txt
  script:
    - snyk test

snyk-code-test-job:
  image:
    snyk/snyk-cli:python-3.9
    # registry.gitlab.com/mambucom/product/sre/release-engineering/selfmanagedservices/tools/docker/snyk/snyk-cli:python-3.9
  stage: test
  before_script:
    - pip3 install -e .
  script:
    - snyk code test
